### ISSUE TITLE
Sample.html

### ISSUE THREAD

**Issue by Pr0gramist** [payeezy/payeezy_js#1]
Line 71 should be /div rather than div, in sample.html as well as the pdf tutorial

**Comment by rohitrajagopal** [comment]
Thank you for bringing it to our notice. We will make the change.

**Comment by deepumi** [comment]
Has any one ever tested Sample.Html file?

**Comment by rohitrajagopal** [comment]
Hi Deepu, 
Yes. Are you seeing any issues?

**Comment by deepumi** [comment]
Rohit, Thanks for the response.. 

Would you download the sample.html and try from your end?

**Comment by rohitrajagopal** [comment]
Deepu,
We had some issues earlier but the file we have now should work. 
http://htmlpreview.github.io/?https://github.com/payeezy/payeezy_js/blob/master/example/sample.html

**Comment by rohitrajagopal** [comment]
Extra <div> tag has been removed.

**Comment by deepumi** [comment]
Thank you
