### ISSUE TITLE
Payeezy authorize payment

### ISSUE THREAD

**Issue by sudhirkoimattur** [payeezy/payeezy_js#14]
Hello,

I have integrated payeezy for one of my web application, everything is working fine. Now i am doing with authorize payment type where in the back end admin oa payeezy we can complete the transaction by mentioning the total amount. 

Now I don't want to go back to payeezy admin to complete the transaction instead in my applications admin side itself want to make the complete transaction by calling any suitable api.

How can I accomplish this one.. Is there have any proper api to integrate?

Thanks in advance.

**Comment by rohitrajagopal** [comment]
Hi Sudhir,

Sorry I did not understand the use case. Can you explain in a little more detail?

**Comment by sudhirkoimattur** [comment]
Hello Rohit,

Sorry for the late reply.

If we do the authorize type payment in payeezy, it will show transaction as "Pre-Authorization" in payeezy account and later on if we want to complete the transaction we have to click on complete transaction and then the transaction will be "Tagged Completion".

As shown in screen shot.

![tagged_completion](https://cloud.githubusercontent.com/assets/7428781/15468933/ad1d1982-2104-11e6-9abf-aa92bef11671.JPG)

Now these set off transactions has done through payeezy account.

I have a super admin and multiple admin for my site. Now every time to complete the transaction I don't want to login through payeezy account and complete the transaction, I want this has to be controlled within admin section of my site.

So that admin will manage the complete transaction through my site itself and super admin will only have the access to login and control through payeezy account.

To do so is there have any API's so that I can accomplish the things in following manner.

Thanks for your time.

**Comment by rohitrajagopal** [comment]
@sudhirkoimattur - Yes, we do - http://developer.payeezy.com/payeezy-api/apis/post/transactions/%7Bid%7D-0

**Comment by sudhirkoimattur** [comment]
Hey thank you so much Rohit. It helped me a lot to solve this issue.
