### ISSUE TITLE
Not assigning currency variable in Sample

### ISSUE THREAD

**Issue by volomike** [payeezy/payeezy_js#21]
In your sample_us_v5.1.html, you're not setting the currency variable that you use in this line:

`Payeezy.setcurrency(currency);`

So, it will end up as null and perhaps emit a Javascript error in the Javascript console. I believe the proper thing to set is to hard-code it to `'USD'` since it's in the US file. However, on the International script, the dropdown sets the currency and it uses that variable to set this object method.

Also, it's kind of odd that all the other Payeezy object methods use camelBack case like `setAuth()` and `setApiKey()`, but `setcurrency()` is all lowercase.

**Comment by rohitrajagopal** [comment]
@renjy01 - Can you take a look at this?

**Comment by rohitrajagopal** [comment]
@volomike - Line 164- 168 is where the currency is being set. The term "US" in the filename is only to say that it is to be used by US merchants. They can ofcourse accept many currencies, not just USD. So, hard coding USD would not be proper. 

setcurrency() has now been renamed to setCurrency to be consistent.
