### ISSUE TITLE
Full code example

### ISSUE THREAD

**Issue by ahkelly** [payeezy/payeezy_js#5]
Re Issue #4 

I do not see the question Jorge asked answered, you closed it with a link that does not answer his question. The link only shows how to generate a token NOT make a transaction such as a payment request once you have received the token. Please post a complete code example rather than only half the equation. It would be most helpful and appreciated.

**Comment by nohup-atulparmar** [comment]
nodeJS (https://github.com/payeezy/payeezy_direct_API/tree/master/payeezy_node/example/lib) sample code has details for authorize and Purchase payment transactions
