### ISSUE TITLE
this.auth is undefined

### ISSUE THREAD

**Issue by gkaran** [payeezy/payeezy_js#6]
In createToken `this.auth` is being used. Although there is no other way to set the auth attribute except doing `Payeezy.auth = <value>`.

Either a `setAuth` function should be introduced or auth should be acquired from `r` as well.

**Comment by rohitrajagopal** [comment]
Thank you @gkaran. We are working on your feedback.

**Comment by rohitrajagopal** [comment]
@gkaran we added a setAuth() method now.

**Comment by gkaran** [comment]
Correct me if I'm wrong but shouldn't you add it in `javascript/payeezy_v3.2.js` instead of `example/payeezy_v3.2.js`?

Also perhaps some cleaning up should be done in the repository and avoid using duplicate files when you can refer to them using a relative path. For example instead of having the js files both in `examples` and `javascript` you can only have them in `javascript`

**Comment by nohup-atulparmar** [comment]
you can download payeezy_v3.2.js from javascript or example folder. both location will work for you.
